version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - $HOME/.aws:/root/.aws
      - $HOME/.ssh:/root/.ssh
    environment:
      - ENVIRONMENT=development
      - FLASK_ENV=development  # デバッグモードを有効にする
    depends_on:
      - db

  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=localdb
      - POSTGRES_USER=localuser
      - POSTGRES_PASSWORD=localpassword

volumes:
  postgres-data:

